AllCops:
  Exclude:
    - metadata.rb
    - bundle_bin/**/*
    - berks-cookbooks/**/*
    - .kitchen/**/*
    - .bundle/**/*
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/DotPosition:
  EnforcedStyle: trailing
